name: PKGBUILD CI

on: [push, pull_request]

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg Build and Check
      id: makepkg
      with:
         makepkgArgs: "-s  --skippgpcheck -f"
      uses: edlanglois/pkgbuild-action@v1
    - name: Print Package Filesz
      run: |
        echo "Successfully created the following package archive"
        echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
    # Uncomment to upload the package as an artifact
    # - name: Upload Package Archive
    #   uses: actions/upload-artifact@v2
    #   with:
    #     path: ${{ steps.makepkg.outputs.pkgfile0 }}
    - name: Move Packages
      run: |
        mkdir packages
        cp ./*.zst ./packages
    - name: Zip the Build
      run:  | 
        sleep 30s
        zip -r ./5.18.5.zip ./packages
      
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: TODO New Release.
        draft: false
        prerelease: false
        files:
          ${{ secrets.ReleaseZipName }}.zip
          LICENSE 
      
