name: PKGBUILD CI

on: [push, pull_request]

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: archlinux
      run: |
        sudo echo -e '\n[archlinuxcn]\nServer = https://mirrors.bfsu.edu.cn/archlinuxcn/$arch' | sudo tee -a /etc/pacman.conf
        sudo pacman -Sy && sudo pacman -S archlinuxcn-keyring
    - name: Makepkg Build and Check
      id: makepkg
      with:
         makepkgArgs: "-s  --skippgpcheck -f"
      uses: edlanglois/pkgbuild-action@v1
    - name: Print Package Filesz
      run: |
        echo "Successfully created the following package archive"
        echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
    - name: Upload Package Archive
      uses: actions/upload-artifact@v2
      with:
        path: ./*.zst
    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: v5.18.6
        title: v5.18.6
        prerelease: false
        files: |
          ./*.zst
      
