name: PKGBUILD CI

on: [push, pull_request]

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg Build and Check
      id: makepkg
      with: 
        makepkgArgs: -s --skippgpcheck -f
      uses: Pinghigh/pkgbuild-action@v3.5
    - name: Print Package Files
      run: |
        echo "Successfully created the following package archive"
        echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
        # Uncomment to upload the package as an artifact
    - name: Upload Package Archive
      uses: actions/upload-artifact@v2
      with:
        path: ${{ steps.makepkg.outputs.pkgfile0 }}
    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: v5.18.9
        title: v5.18.9
        prerelease: false
        files: |
          ./*.zst