name: PKGBUILD CI

on: [push, pull_request]

jobs:
  pkgbuild:
    runs-on: archlinux-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Archlinux
      runs:
        using: 'docker'
        image: 'Dockerfile'
    - name: Makepkg Build and Check
      id: makepkg
      run: bash mkpkg.sh
    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: v5.18.6
        title: v5.18.6
        prerelease: false
        files: |
          ./*.zst
      
